### ISSUE TITLE
Change the number of input points

### ISSUE THREAD

**Issue by xingruiy** [JuanDuGit/DH3D#5]
Thanks for the great work

I have a question regarding network structure: is it possible to change to input point number without re-training the network from scratch? Thanks

**Comment by rui2016** [comment]
Hi @xingruiy,

you can modify "num_points" in the config files:
https://github.com/JuanDuGit/DH3D/blob/master/models/local/config.json
https://github.com/JuanDuGit/DH3D/blob/master/models/global/config.json

After you change this number to x, the network will assume it to be the size of all the input point clouds. Each input point cloud will first be sampled using a voxel grid. If the number of points is smaller than x after sampling, the point cloud will be padded; if larger than x, only x points will be used. 

So the pre-trained model can be directly applied on point clouds with different sizes. However, the performance is not guaranteed. The density of the point clouds will influence the local descriptor, and this will further influence the global descriptor. Additionally the global descriptor is also correlated to the coverage of the point clouds. 

Hope this is useful.

**Comment by xingruiy** [comment]
@rui2016  Many thanks!
