### ISSUE TITLE
Question about model runtime and relocalization process

### ISSUE THREAD

**Issue by Noam-M** [JuanDuGit/DH3D#6]
I am curious to hear about the runtime and hardware that you used. You have stated in the paper that for a point cloud with 8192 points, one forward pass took 80ms but I did not see any hardware specifications, or information about the training time, hardware and parameters.
Another question concerns the point-cloud-based relocalization process itself. I know about implementing image-based relocalization, and will be very glad to hear how you are implementing the point-cloud-based relocalization. 

Much appreciated! Thanks!

**Comment by rui2016** [comment]
Hi @Noam-M,

the network was trained and tested on a Nvidia Titan X. The training took around 3 days in total. All the parameters are listed in Sec 4 of the main paper and Sec 4.3 of the supplementary material. 

Regarding the second part of your comment, could you be more specific? I believe most of the details of our pipeline are provided in the paper, but would like to add here if something useful is missing.
