### ISSUE TITLE
Point Cloud Retrieval for DSO

### ISSUE THREAD

**Issue by manuel-88** [JuanDuGit/DH3D#9]
Hello,

did you also validate the point cloud retrieval for DSO? As far as I can see in the paper for DSO only the point cloud registration is validated. 

Regards

**Comment by rui2016** [comment]
Hi @manuel-88,

yes you are right, we didn't run point cloud retrieval for DSO point clouds. However, you can try it yourself possibly using the DSO point clouds provided for point cloud registration provided here https://vision.in.tum.de/research/vslam/dh3d.

Cheers
Rui
